name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "**/*.swift"
  workflow_dispatch:

concurrency:
  group: "ci-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
  XCODE_SCHEME: "StarlingRoundUp"
  IOS_DESTINATION: "platform=iOS Simulator,name=iPhone 15,OS=17.5"
  TEST_PLAN: "StarlingRoundUp"
  UI_TEST_PLAN: "StarlingRoundUpUI"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail && NSUnbufferedIO=YES \
          xcodebuild clean build-for-testing \
            -scheme ${{ env.XCODE_SCHEME }} \
            -destination '${{ env.IOS_DESTINATION }}' \
            -testPlan '${{ env.TEST_PLAN }}' | xcbeautify --renderer github-actions
      
      - name: Test
        run: |
          set -o pipefail && NSUnbufferedIO=YES \
          xcodebuild test-without-building \
            -scheme ${{ env.XCODE_SCHEME }} \
            -destination '${{ env.IOS_DESTINATION }}' \
            -testPlan '${{ env.TEST_PLAN }}' | xcbeautify --renderer github-actions
